### ISSUE TITLE
Database setup

### ISSUE THREAD

**Issue by Marwasel** [DIT113-V22/group-12#10]
User story: As a customer, I want to be able to store my personal information(username and password),  records of orders or transactions so that I can easily refer to them when I need to.

Acceptance criteria: The system should allow users to store their information in the system so that they can easily log in when using the app.

**Comment by platisd** [comment]
The "acceptance criteria" is what should be actually reflected in the user story. The "developer" is not a user of the system and storing data in json files isn't inherently valuable.
