### ISSUE TITLE
Update the documentation with Sprint 1 and 2 retrospectives.

### ISSUE THREAD

**Issue by d0nate110** [DIT113-V22/group-12#87]
Update the documentation with Sprint 1 and 2 retrospectives, so that the Product Owner is aware of challenges and improvements during each Sprint. 

Acceptance criteria: The screenshots of retrospective boards from InVision app are added to the readme file.

**Comment by Marwasel** [comment]
https://github.com/DIT113-V22/group-12/wiki/Documentation#retrospectives
